### ISSUE TITLE
Multiple colors

### ISSUE THREAD

**Issue by emilwibe** [VincentGarreau/particles.js#129]
Is it possible to add multiple colors for the particles?

**Comment by twanlass** [comment]
Heya @emilwibe - you can pass an array of colors like this:
```
    "color": {
      "value": ["#BD10E0","#B8E986","#50E3C2","#FFD300","#E86363"]
    }
```

**Comment by emilwibe** [comment]
@twanlass thanks you so much. This is great :)

**Comment by Ammarkashmiri** [comment]
but it is not working on linked lines?? can you have a solution for it?

**Comment by jezaman** [comment]
Please add support for linked lines too.
