### ISSUE TITLE
Destroy method not working?

### ISSUE THREAD

**Issue by dingo-d** [VincentGarreau/particles.js#147]
I am initializing multiple particle instances like this

```
function initialize_particles(){
    particlesJS.load('particles_1', my_particles.particles_json);
    particlesJS.load('particles_2', my_particles.particles_json);
    particlesJS.load('particles_3', my_particles.particles_json);
    particlesJS.load('particles_4', my_particles.particles_json);
    particlesJS.load('particles_5', my_particles.particles_json);
}
```

they are inside `#particles_1`... elements.

I would like to destroy them if the screen size iz smaller than 700px so I tried

```
$(window).on('resize', function(){
    if ($(window).width() > 700) {
        initialize_particles();
    } else {
        particlesJS.fn.vendors.destroy();
    }
});
```

The initialization part works (I see them recreating when resizing the screen), but destroying them will give me 

> Uncaught TypeError: Cannot read property 'vendors' of undefined 

I tried with `pJS` instead of `particlesJS`, I tried with `particlesJS.destroy()`, nothing worked. What am I doing wrong here?

**Comment by dwinnbrown** [comment]
I've got the exact same issue...did you fix it?

**Comment by ArthurGerbelot** [comment]
Did you try 
`pJSDom[0].pJS.fn.vendors` ? 

Also I didn't found any `vendors.destroy()` function, but an `vendors.destroypJS()` (maybe what you're looking for).

Second choice, the #158 could help you.

**Comment by dingo-d** [comment]
Hi, I stopped working on the project that was using this, don't remember how we ended up fixing this, but thanks for the reply, it could prove useful to some maybe :) I'll close the issue.
