### ISSUE TITLE
Is there a way to improve performance for facebook in-app browser?

### ISSUE THREAD

**Issue by EzraLopez** [VincentGarreau/particles.js#171]

**Comment by Julix91** [comment]
What does this even mean? Are you using particles.js on facebook (in a browser app on your mobile phone)?

**Comment by EzraLopez** [comment]
My bad, I was too vague. I'm talking about accessing my website from the Facebook Android app. Facebook has an in-app browser to open links from its Android app by default. My website has a centered div and the particles as the background of the entire page (see [https://elopez.me](elopez.me)). The issue I'm having is that particles just randomly flicker, stop and reset on top of my centered div, then animations continue working normally. Honestly, it is kind of cool sometimes because it makes look like there's lighting on top of the div, but I definitely did not intend it that way. I believe it is a performance issue, but I might be wrong.

**Comment by Julix91** [comment]
use @media and just display a jpg for cellphones, maybe?

**Comment by EzraLopez** [comment]
Thanks for the suggestions! Actually, I just solved it. I optimized the mobile site enough so I could I still use the particle background.

Cheers!
