### ISSUE TITLE
How can I use particles.js with fullpage.js?

### ISSUE THREAD

**Issue by RobotSe7en** [VincentGarreau/particles.js#199]
I want to show particles.js in each section of fullpage.js. How can I do that?

**Comment by RobotSe7en** [comment]
I already know how to do. So I closed this issue. Thank you!

**Comment by JorgeAriel** [comment]
how did you do it

**Comment by gupta-ji6** [comment]
Hello @RobotSe7en 😃  
Can you please **share** how you used particles.js with fullpage.js?

**Comment by almaszaurbekov** [comment]
Just use your **ParticleJS** inside of your _Section_:
`<div id="fullpage">
		<div class="section" id="section-0">
			<div id="particles-js"></div>
		</div>
	</div>`
