### ISSUE TITLE
Giving type error in console

### ISSUE THREAD

**Issue by ApCoder123** [VincentGarreau/particles.js#204]
I have tried to use particles.js on my site, and when running locally, the particles don't appear, and this shows in the console `particles.js:1 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at window.particlesJS (particles.js:1)
    at script.js:9
`
User Agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`

**Comment by cworf** [comment]
I am also getting this same thing, assuming you figured it out since you closed it. would you mind sharing the solution?
