### ISSUE TITLE
Particles and React

### ISSUE THREAD

**Issue by NoelAnnParisi** [VincentGarreau/particles.js#213]
Let me start by saying I love this library! I am trying to get this to work with React. I'm calling 
` particlesJS.load('particles-js', '../assets/particles.config.json', function() {
      console.log(callback - particles.js config loaded');
    });`
 inside the componentDidMount ion my Main container, but am getting this error
`_particles2.default.load is not a function ` in my console. The package is downloaded and imported in on my file. 

In my HTML file, I've given the body an id of particles-js (so as not to conflict with the div id of app for React in the body)

I would love any suggestions! Thanks so much :)

**Comment by NoelAnnParisi** [comment]
and my JSON code is in the file referenced in the function

**Comment by NoelAnnParisi** [comment]
Found your other library! Thanks :)

**Comment by wahlforss** [comment]
Which library?

**Comment by prayatna** [comment]
maybe this one https://github.com/Wufe/react-particles-js ?
