### ISSUE TITLE
particlesJS not defined

### ISSUE THREAD

**Issue by TheSoulrester** [VincentGarreau/particles.js#218]
```
Uncaught ReferenceError: particlesJS is not defined
    at (index):911
```

This is my Code: 
```
<div id="particles-js"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.0.2/particles.min.js"></script>

<script type="text/javascript">
/* particlesJS.load(@dom-id, @path-json, @callback (optional)); */
particlesJS.load('particles-js', 'bilder/particlesjs-config.json', function() {
  console.log('callback - particles.js config loaded');
});
</script>
```

whats wrong?

**Comment by TheSoulrester** [comment]
wrong cdn - sry ;)

**Comment by rico-ocepek** [comment]
same lol

**Comment by dapseen** [comment]
Looking for the correct CDN?
https://www.jsdelivr.com/package/npm/particles.js

THe one on cloudflare is misleading

**Comment by dwale** [comment]
@dapseen can you give me a resource or link to help implement it, i keep getting the error  **particlesJS is not defined**

**Comment by dwale** [comment]
and i used the right CDN , I'm using Angular 5

**Comment by dapseen** [comment]
@dwale https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js here you go

**Comment by subinedge** [comment]
<div id="particles-js"></div>
  

  <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <script>
      particlesJS.load('particles-js', 'js/particle.json', function() {
        console.log('che che che');
        
      });
    </script>

I am getting a strange error 
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.s.onreadystatechange (particles.js:1530)

s.onreadystatechange | @ | particles.js:1530
   XMLHttpRequest.send (async) 
   window.particlesJS.load @particles.js:1539 (anonymous)

**Comment by danieldanielecki** [comment]
I'm getting this when using Server-Side Rendering (SSR) with Angular Universal, anyone knows how to find a workaround for this? Tried to whitelist in webpack nodeExternals, but stil lthe same error.

**Comment by biennui1998mu** [comment]
> I'm getting this when using Server-Side Rendering (SSR) with Angular Universal, anyone knows how to find a workaround for this? Tried to whitelist in webpack nodeExternals, but stil lthe same error.

me too! Did you find the way resolve ??

**Comment by danieldanielecki** [comment]
> > I'm getting this when using Server-Side Rendering (SSR) with Angular Universal, anyone knows how to find a workaround for this? Tried to whitelist in webpack nodeExternals, but stil lthe same error.
> 
> me too! Did you find the way resolve ??

I'm having this error, but the code is working fine. I'm on NestJS/Cloud Functions for Firebase setup for the SSR.

**Comment by Creator674** [comment]
solve it by adding **"window"** before.
<img width="575" alt="Снимок экрана 2020-11-23 в 21 00 37" src="https://user-images.githubusercontent.com/43150028/99997951-f1500c00-2dce-11eb-8e92-99e091bc6bfe.png">

**Comment by zakariya6002** [comment]
this is some error hard to figure out but easy to use
