### ISSUE TITLE
Feature: fadein

### ISSUE THREAD

**Issue by Mudox** [VincentGarreau/particles.js#23]
Hi, Vincent.

Thanks very much for this great project.

Is there any way to specify particles to _fade in_ one by one or in step ones, or fade in by opacity.

**Comment by VincentGarreau** [comment]
Thank you!
Added into the 1.1.0 version :) https://github.com/VincentGarreau/particles.js/releases/tag/1.1.0

**Comment by Mudox** [comment]
:+1:
