### ISSUE TITLE
Can someone explain me how can i attach this at my website.

### ISSUE THREAD

**Issue by anmol27katyani** [VincentGarreau/particles.js#236]
Hello,
I want to use this particles.js as my main content holder for my upcoming project.
Sorry for being a noob here, but this will be my first experience using such library if anyone can explain me the process.
@pborreli @icodeforlove @csu @victorbstan @kkirsche 
I'll be highly thankful to you.

**Comment by amarkrsinha** [comment]
hey buddy you can get some tutorials on particle.js on youtube there are bunch of them which experiment one is online tutorial(a youtube channel ) do check it particle.js playlist

**Comment by anmol27katyani** [comment]
@amarkrsinha  I am really thankful to you for this
You were of great help. 👍
