### ISSUE TITLE
How to make Particles.js responsive? 

### ISSUE THREAD

**Issue by KoustavFrost** [VincentGarreau/particles.js#268]
I want to add the particles snow effect on my website. Everything is fine but it is not working for phones. Can anyone help me?

**Comment by segg21** [comment]
Do you know what responsive means? The canvas should always resize when window size changes. On mobile, there shouldn’t be an issue. Just make sure after you applied the settings, you atleast focus on the canvas.

**Comment by KoustavFrost** [comment]
Ohh. Thanks for helping me out. I a pretty beginner and trying to learn new stuff.

**Comment by Bullkn0x** [comment]
I am having a similar issue with responsiveness of the particles as well as the mouse location on window size change.  Here are examples of what is occuring.

Before screen size change: 
https://media.giphy.com/media/xBpGtoZh7l6PAbmlpi/giphy.gif

After:  (mouse location moves, and scale of lines/nodes are different)
https://media.giphy.com/media/khOqDEduaH6GsTFBYq/giphy.gif

**Comment by zsdotmodus** [comment]
Hi,
In case someone else ends up looking for this.


/* ===================================================================
   Original by - Eric Meyer
 =================================================================== */

html,body,div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,figcaption,figure,footer,header,hgroup,menu,nav,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}
body{line-height:1}
article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}
nav ul{list-style:none}
blockquote,q{quotes:none}
blockquote:before,blockquote:after,q:before,q:after{content:none}
a{margin:0;padding:0;font-size:100%;vertical-align:baseline;background:transparent;text-decoration:none}
mark{background-color:#ff9;color:#000;font-style:italic;font-weight:bold}
del{text-decoration:line-through}
abbr[title],dfn[title]{border-bottom:1px dotted;cursor:help}
table{border-collapse:collapse;border-spacing:0}
hr{display:block;height:1px;border:0;border-top:1px solid #ccc;margin:1em 0;padding:0}
input,select{vertical-align:middle}
li{list-style:none}


/* =============================================================================
   My CSS
   ========================================================================== */

/* ---- base ---- */

html,body{ 
	width:100%;
	height:100%;
	background:#111;
}

html{
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}

body{
  width: 100%;
  height: 100%;
  font:normal 75% Arial, Helvetica, sans-serif;
}

canvas{
  width: 100%;
  height: 100%;
  display:block;
  vertical-align:bottom;
}


/* ---- particles.js container ---- */

#particles-js{
  width: 100%;
  height: 100%;
  background-color: #EDEDED;
  background-image: url('');
  background-size: cover;
  background-position: 50% 50%;
  background-repeat: no-repeat;
}

**Comment by ZSchalkwykPrivate** [comment]
Hi,
In case someone else ends up looking for this.

/* ===================================================================
Original by - Eric Meyer
=================================================================== */

html,body,div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,figcaption,figure,footer,header,hgroup,menu,nav,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}
body{line-height:1}
article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}
nav ul{list-style:none}
blockquote,q{quotes:none}
blockquote:before,blockquote:after,q:before,q:after{content:none}
a{margin:0;padding:0;font-size:100%;vertical-align:baseline;background:transparent;text-decoration:none}
mark{background-color:#ff9;color:#000;font-style:italic;font-weight:bold}
del{text-decoration:line-through}
abbr[title],dfn[title]{border-bottom:1px dotted;cursor:help}
table{border-collapse:collapse;border-spacing:0}
hr{display:block;height:1px;border:0;border-top:1px solid #ccc;margin:1em 0;padding:0}
input,select{vertical-align:middle}
li{list-style:none}

/* =============================================================================
My CSS
========================================================================== */

/* ---- base ---- */

html,body{
width:100%;
height:100%;
background:#111;
}

html{
-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}

body{
width: 100%;
height: 100%;
font:normal 75% Arial, Helvetica, sans-serif;
}

canvas{
width: 100%;
height: 100%;
display:block;
vertical-align:bottom;
}

/* ---- particles.js container ---- */

#particles-js{
width: 100%;
height: 100%;
background-color: #EDEDED;
background-image: url('');
background-size: cover;
background-position: 50% 50%;
background-repeat: no-repeat;
}
