### ISSUE TITLE
Remove bower, add yarn

### ISSUE THREAD

**Issue by favna** [VincentGarreau/particles.js#294]
For some time now Bower has recommending users to change to the Yarn package manager as opposed to using Bower as can be seen in this blog post: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

I would therefore recommend removing the bower entry from the readme and instead list an entry for using Yarn.

**Comment by samsch** [comment]
The npm instructions generally cover yarn as well.

**Comment by mtpiercey** [comment]
Basically replace 
```npm install``` with ```yarn```, 
```npm run x``` with ```yarn x```, 
```npm install --save x``` with ```yarn add x```,
and ```npm install -g x``` with ```yarn global add x```
 and you should be fine. 

Until one or both of them get major updates or they eventually replaced by the next big thing. The only constant in the JS world, it seems, is that JS keeps changing.

**Comment by favna** [comment]
I closed this issue since it was stale but I'll just say this.

My primary point was to remove Bower since it's deprecated. I quite frankly couldn't care less if you add Yarn instructions or not (as much as I prefer Yarn over NPM), but the fact that Bower is deprecated by it's creators is an immutable fact.

---

Furthermore a year ago I was a noob in webdev and JS compared to these days to be honest so that was also another motivator for me to close the issue - the fact that it maybe partially unfounded
