### ISSUE TITLE
Particles.js behind some pre-existing HTML

### ISSUE THREAD

**Issue by GreemDev** [VincentGarreau/particles.js#295]
Hey there! I was wondering how I could put P.js behind my existing HTML. My HTML is https://greemdotcs.github.io - and the source for my HTML is on my repo for that website, https://github.com/greemdotcs/greemdotcs.github.io/ - Thanks!

**Comment by lsbyerley** [comment]
@GreemdotCS  Don't wrap all of your html in the particles-js div. Just do `<div id="particles-js"></div>` and then set the styling to:

    #particles-js {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 1;
    }

Then, be sure to set `z-index:2;` on the other elements you want in front of the particles

**Comment by GreemDev** [comment]
it doesn't appear in front; just at the top of the page

**Comment by kgalka** [comment]
Hi GreemdotCS,
I simply added position: fixed; top: 0; in the inspector, and particles appear in front.

**Comment by GreemDev** [comment]
Still isn't working. Also, my website has moved to https://greem.xyz - Thanks!

**Comment by GreemDev** [comment]
And sorry for my super inactivity, :p

**Comment by Markyroson** [comment]
> @GreemdotCS Don't wrap all of your html in the particles-js div. Just do `<div id="particles-js"></div>` and then set the styling to:
> 
> ```
> #particles-js {
>   position: absolute;
>   top: 0;
>   left: 0;
>   width: 100%;
>   height: 100%;
>   z-index: 1;
> }
> ```
> Then, be sure to set `z-index:2;` on the other elements you want in front of the particles

Thank you so so much for posting that. It solved the issue I was having (same one as OP, though unfortunately it didn't help them for some reason).

**Comment by GreemDev** [comment]
Eh, I've remade my site 2 times since I posted that. :P

**Comment by Markyroson** [comment]
> Eh, I've remade my site 2 times since I posted that. :P

So is it resolved for you now?

**Comment by GreemDev** [comment]
would've expected that to be obvious, but yeah. my new site doesn't use particles.js
