### ISSUE TITLE
Auto density on mobile?

### ISSUE THREAD

**Issue by andrea-ligios** [VincentGarreau/particles.js#299]
Hi, I'm not sure where to find the `auto ` setting for density on mobile introduced in version 1.1.0 as described here https://github.com/VincentGarreau/particles.js/issues/30#issuecomment-74485635

Is it still there?

**Comment by garbinmarcelo** [comment]
@andrea-ligios Were you able to be responsive? I can not leave it at full height. =/

stay at the top! =S
![image](https://user-images.githubusercontent.com/9335588/39733255-3dad99ba-5248-11e8-94d7-1aff8fa0f064.png)

**Comment by andrea-ligios** [comment]
Yes, I was. 
You need to play with the `position` attribute (and eventually `z-index` if needed). 
Cheers
