### ISSUE TITLE
How to decrease density of particles on mobile screen?

### ISSUE THREAD

**Issue by rahulsimpact** [VincentGarreau/particles.js#30]
Hey Vincent Thanks for this :)
I am having a little problem as
Your online preview " http://vincentgarreau.com/particles.js/ "  looks so smooth  on all screens.
When I am running file  locally(in small screens) i get the view as
![particles js](https://cloud.githubusercontent.com/assets/4784981/5139058/ec51245e-717e-11e4-9538-47d741be5d74.png)

The particles are condensing too much on the sides of window when i resize the window 
Could you please help me where I am missing out to get a smooth view like yours?

**Comment by nOttenga** [comment]
This is a great plugin. I walked on this mobile density "problem" and i solved like this, transforming it in something responsive.

width = $(document).width();
        num_nb = Math.round(Math.sqrt(width * 15));
        console.log(num_nb)

         particlesJS('particles-js', {
            particles: {
                color: '#008391',
                shape: 'circle', // "circle", "edge" or "triangle"
                opacity: .6,
                size: 5,
                size_random: true,
                nb: num_nb,
                line_linked: {
                    enable_auto: true,
                    distance: 110,
                    color: '#008391',
                    opacity: 1,
                    width: 1,
                    condensed_mode: {
                        enable: false,
                        rotateX: 600,
                        rotateY: 600
                    }
                },
                anim: {
                    enable: true,
                    speed: 1
                }
            },
            interactivity: {
                enable: true,
                mouse: {
                    distance: 250
                },
                detect_on: 'canvas', // "canvas" or "window"
                mode: 'grab',
                line_linked: {
                    opacity: .5
                },
                events: {
                    onclick: {
                        enable: false,
                        mode: 'push', // "push" or "remove" (particles)
                        nb: 4
                    }
                }
            },
            /* Retina Display Support */
            retina_detect: true
        });

**Comment by VincentGarreau** [comment]
Hey,

Great solution @nOttenga, thank you!

The plugin has now a "responsive mode". With the v1.1.0 version, you can enable a "density_auto" param to "true", and set a "density_area". The number of particles on the screen depends on this "density_area":

number of particles on the screen = pJS.particles.nb * (canvas width *  canvas height / 1000) / density_area

Hope this helps :)

**Comment by ummahusla** [comment]
@nOttenga Awesome solution mate! Thank you.

**Comment by david-soyez** [comment]
Doesn't work as expected on mobile the density is not the same as desktop for the same values.
