### ISSUE TITLE
Multiple particlesJS

### ISSUE THREAD

**Issue by Spharian** [VincentGarreau/particles.js#33]
Hi,
I'm trying to apply your plugin on multiple IDs, works fine for drawing it, but only the last created canvas is interactive/animated. Do you have any solution?

Thanks :)

**Comment by VincentGarreau** [comment]
Hi,
Sorry for the delayed reply. Unfortunately I don't have enough time to keep the plugin, my apologies.

The plugin (v1.0.3) does not support multiple canvas element on the same page. For this, it would set the requestAnimFrame function + several interactions (mousemove, click, etc.) to each canvas. It is possible to create different canvas, but without animation and without interactivity. I'll study it ;)

**Comment by joshfarrant** [comment]
Would also love to see this

**Comment by joshdickson40** [comment]
Would you accept a PR for this?

**Comment by joshdickson40** [comment]
Or if you don't have time would you be open to a new maintainer? This is a great start and I'd love to be able to add to what you've got.

**Comment by VincentGarreau** [comment]
Supported in the 2.0.0 version https://github.com/VincentGarreau/particles.js/releases/tag/2.0.0 ;)

**Comment by carlosnpz** [comment]
How to implement this? Didn't find in the documentation...
