### ISSUE TITLE
How I can set a size for <canvas> element? 

### ISSUE THREAD

**Issue by Pestov** [VincentGarreau/particles.js#37]
By default <canvas> has width and height at 100%. How can I change it?

**Comment by SamHH** [comment]
You can actually use these as configurable parameters. Whether that's new or not I don't know.

Example (obviously substitute 500px for whatever you'd like):

'''
particlesJS('particles-js', {
  canvas: {
    w: "500px",
    h: "500px"
  },
  // rest of code
});
'''

**Comment by Pestov** [comment]
@SamHH I think that it's already been, because releases not contain information of this method. But I don't know about that. Thanks!

**Comment by reginpv** [comment]
Here's what worked for me:

```
/* particlesJS.load(@dom-id, @path-json, @callback (optional)); */
    particlesJS.load('particles-js', '/vendors/particles.js-master/particles.json', function() {
      let el = document.querySelector(".particles-js-canvas-el"); 
      el.setAttribute("height", "300px");
    });
```
