### ISSUE TITLE
Changing Background Color

### ISSUE THREAD

**Issue by Afsana1313** [VincentGarreau/particles.js#397]
Hello everyone,
I am working with particles.js. I am trying to change the background color in app.js by changing the color code of config_demo->background_color. But I am unable to do this. Instead of changing background color in the CSS file, is there any other way around?

**Comment by tisaconundrum2** [comment]
Couldn't you just change the colors from the configuration screen of 
https://vincentgarreau.com/particles.js/

![image](https://user-images.githubusercontent.com/11879769/69501936-0564e300-0ec7-11ea-8e55-349ae260f89c.png)

**Comment by Afsana1313** [comment]
I could do this definitely. I just asked if there is any other option. I was thinking if there is any way to change the background color of the canvas without using CSS rules.

**Comment by skywalker-its** [comment]
hello , everyone 
I am working on github. I am trying to change the background color 
what could i do

**Comment by matteobruni** [comment]
Checkout tsParticles, it has a `background` options, like described [here in the wiki](https://github.com/matteobruni/tsparticles/wiki/tsParticles-Options-Background)
