### ISSUE TITLE
Using fontawsome with particle.js

### ISSUE THREAD

**Issue by ghost** [VincentGarreau/particles.js#398]
Hi @VincentGarreau and @everyone,

How would I achieve using fontawesone icons floating around instead of particles?

I would appreciate anyone's help on this?

**Comment by matteobruni** [comment]
You can switch to [tsParticles](https://github.com/matteobruni/tsparticles) and they have the support like this: https://dev.to/matteobruni/fontawesome-loves-tsparticles-34pn

[tsParticles](https://github.com/matteobruni/tsparticles) are fully compatible with particles.js, you just need to change the script source!
