### ISSUE TITLE
How to import from node_modules?

### ISSUE THREAD

**Issue by kien5436** [VincentGarreau/particles.js#401]
After installing this package via npm, how can I import it to my .js file? I want to load it from node_modules.

`import 'particles.js'` does not work.
I have to copy `particles.js` to my folder like this:
```
node_modules/
  particles.js/
    particles.js
src/
  js/
    myfile.js
    particles.js // copied from above
```
then: `import './particles.js'` and now it works, but it's very inconvenience.

**Comment by matteobruni** [comment]
Hi @shhlkien if you need an import/require library you can try [this](https://github.com/matteobruni/tsparticles)

**Comment by kien5436** [comment]
> Hi @shhlkien if you need an import/require library you can try [this](https://github.com/matteobruni/tsparticles)

Thank you, I found the way to import it, but I'll try your module sometime

**Comment by permanaj** [comment]
Hi @kien5436 , how did you import without copying it to the project folder?

**Comment by kien5436** [comment]
> Hi @kien5436 , how did you import without copying it to the project folder?

@permanaj 

it's been too long since I asked this question. I just remember that I used webpack 

If you want to see more details, you can visit my repo: https://github.com/kien5436/eightplus/tree/dev
