### ISSUE TITLE
FR: Image Decals

### ISSUE THREAD

**Issue by hitchcott** [VincentGarreau/particles.js#42]
Excellent library, but it seems like it doesn't support images being used for the particles (with sizing etc), rather than just a solid color.

Would be a great addition in my opinion.

**Comment by VincentGarreau** [comment]
Interesting idea, I'll study it. Thanks @hitchcott !

**Comment by hitchcott** [comment]
Turns out it's pretty easy to implement; here's quick workaround I made:

```
// particles.js : 292
    if(pJS.particles.shape === 'image'){ // replace with a non-hack
      var image = new Image();
      image.src = '/bubble_decal.png';
      pJS.canvas.ctx.drawImage(image, this.x - this.radius, this.y - this.radius, this.radius*2, this.radius*2);
    }else{
    // deal with shapes
```

Cool, looking forward to an official version though

**Comment by VincentGarreau** [comment]
Images supported since the 2.0.0 version, thanks for the issue ;)
https://github.com/VincentGarreau/particles.js/releases

Next step: Support multiple images (support just one for now)
