### ISSUE TITLE
React Particle js width and height incorrect scaling with Transitions

### ISSUE THREAD

**Issue by devdominus** [VincentGarreau/particles.js#445]
This is an issue I face with using react-particle-js in mobile responsive view. The width and height set to the screens width and height initially. But on transitioning to another page and coming back, the width and height becomes double the screens width and height making the particle js animation look bad.

**Comment by matteobruni** [comment]
Maybe you want to open an issue on the right library https://github.com/Wufe/react-particles-js

**Comment by devdominus** [comment]
Oh ok thank you
