### ISSUE TITLE
NOT GETTING OTHER DIVS OVER THE BACKGROUND

### ISSUE THREAD

**Issue by Aagam-Jain-113** [VincentGarreau/particles.js#451]
I have used the same code as you used but i want to use this as background but i am getting my div elements below my background. These divs must be on the same page. how to do that can anyone help?

**Comment by SampaioPedroDev** [comment]
@Aagam-Jain-113 I want to do the same, how did you do it?

**Comment by Aagam-Jain-113** [comment]
HTML part
`<div id="particles-js"></div>`
CSS part 
`*{
z-index: 2;
}
#particles-js{
  width: 100%;
  height: 100%;
  z-index: -1;
  overflow: hidden;
  background:#19B5FE ;
  background-size: cover;
  position: fixed;
}`
and added the particle.js file. and 
Check this video for reference: https://www.youtube.com/watch?v=TJY45v_QF34
Edit: Write the HTML part at the starting of your body section or after the header section.
