### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by akashnimare** [VincentGarreau/particles.js#47]
It's not responsive. What are the options to make it responsive?

**Comment by dabockster** [comment]
Is it the topmost <div> or is there stuff above it in your body tag?

**Comment by akashnimare** [comment]
It is the topmost.

**Comment by VincentGarreau** [comment]
Hi @akashnimare , @dabockster :)

To make it responsive, juste set the "density_auto" option to "true". And with the "density_area" option, you can set an area relative to the defined number of particles.

For example:
```` javascript

particlesJS('particles-js', {
  interactivity: {
    events: {
      onresize: {
        enable: true,
        density_auto: true,
        density_area: 400 // nb_particles = particles.nb * (canvas width *  canvas height / 1000) / density_area
      }
    }
  }
});
````

There is a demo juste here: http://vincentgarreau.com/particles.js/demo

**Comment by akashnimare** [comment]
Thank you!

**Comment by n6ither** [comment]
Hi Vincent, i love particles.
The code you provide about responsiveness, where i need to put it? I have the json file with all the configuration. Thanks!

**Comment by Bullkn0x** [comment]
I am having a similar issue with responsiveness of the particles as well as the mouse location on window size change.  Here are examples of what is occuring.

Before screen size change: 
https://media.giphy.com/media/xBpGtoZh7l6PAbmlpi/giphy.gif

After:  (mouse location moves, and scale of lines/nodes are different)
https://media.giphy.com/media/khOqDEduaH6GsTFBYq/giphy.gif

**Comment by terrencechambers** [comment]
> I am having a similar issue with responsiveness of the particles as well as the mouse location on window size change. Here are examples of what is occuring.
> 
> Before screen size change:
> https://media.giphy.com/media/xBpGtoZh7l6PAbmlpi/giphy.gif
> 
> After: (mouse location moves, and scale of lines/nodes are different)
> https://media.giphy.com/media/khOqDEduaH6GsTFBYq/giphy.gif

Can you post your json and your css.
