### ISSUE TITLE
Particles Covering everything

### ISSUE THREAD

**Issue by px1w** [VincentGarreau/particles.js#473]
When I run particles.js, it messes up everything in the webpage

![image](https://user-images.githubusercontent.com/80988430/123265475-01f66b00-d4f3-11eb-96e7-59325544c4a2.png)
This is it normally

And this is it when i run particles
![image](https://user-images.githubusercontent.com/80988430/123265566-176b9500-d4f3-11eb-856a-47e4fc653f0e.png)
How do i fix this? 

index.html
```
<!DOCTYPE html>
<html lang="en">
<style>
    .Title h1 {
        font-family: 'Product Sans Thin';
        font-size: 80px;
    }
    .Title h2 {
        font-family: 'Product Sans Thin';
        position: relative;
        bottom: 60px;
    }
    .DiscordDiv {
        font-family: 'Product Sans Thin';
    }
</style>
<head>
    <script src =jquery-3.6.0.js></script>
    <script src="particles.js"></script>
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
<div id="particle-div"></div>
<button id="particle-button">Start</button>

<script>
    $("#particle-button").click(function(){
        particlesJS.load('particle-div','particle-cfg.json');
    });
</script>

<div class ="DiscordDiv">
    <button class="Github">
        </button>
</div>
<div class="Background"></div>
<div class="Title">
    <h1>Shea</h1>
    <h2>Cool spaghetti person</h2>
</div>
</body>
</html>
```

**Comment by madhav-madhusoodanan** [comment]
How about you put the particle-button class at a negative z-index in the css?

**Comment by ItsFlash10** [comment]
<!DOCTYPE html>
<html lang="en">
<style>
    .Title h1 {
        font-family: 'Product Sans Thin';
        font-size: 80px;
    }
    .Title h2 {
        font-family: 'Product Sans Thin';
        position: relative;
        bottom: 60px;
    }
    .DiscordDiv {
        font-family: 'Product Sans Thin';
    }
</style>
<head>
    <script src =jquery-3.6.0.js></script>
    <script src="particles.js"></script>
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
<script>
    $("#particle-button").click(function(){
        particlesJS.load('particle-div','particle-cfg.json');
    });
</script>

<div class ="DiscordDiv">
    <button class="Github">
        </button>
</div>
<div class="Background"></div>
<div class="Title">
    <h1>Shea</h1>
    <h2>Cool spaghetti person</h2>
</div>
<div id="particle-div" style = 
                    position: "absolute",
                    top: 0,
                    left: 0,
                    width: "100%",
                    height: "100%",
                    zIndex: '100'> //or z-index
                   </div>
<button id="particle-button">Start</button>
</body>
</html>

**Comment by ItsFlash10** [comment]
position: "absolute",
                    top: 0,
                    left: 0,
                    width: "100%",
                    height: "100%",
                    zIndex: '100'
                    
Add this to the div or css of particle.js
