### ISSUE TITLE
Possible to turn off random colours?

### ISSUE THREAD

**Issue by fbnntt** [VincentGarreau/particles.js#481]
Hi
Just wondering if there's a way to turn off the randomness of colour picking? I have two particles and want to use two colours without the possibility of it showing two the same colour.

Thanks

**Comment by matteobruni** [comment]
Hi @fbnntt,

It’s not possible with particles.js but I made a sample using [tsParticles](https://particles.js.org) which has a `reduceDuplicates` option here: https://codepen.io/matteobruni/pen/gOxwPZY

**Comment by fbnntt** [comment]
This is perfect, thanks so much @matteobruni!
