### ISSUE TITLE
Attract rather than repulse

### ISSUE THREAD

**Issue by anthonycmain** [VincentGarreau/particles.js#485]
Would it be possible to make the particles move towards the mouse rather than away. I've tried a negative value in the direction but that doesnt work

**Comment by matteobruni** [comment]
You can see this sample here: https://codepen.io/matteobruni/pen/bGrXJew

It uses [tsParticles](https://github.com/matteobruni/tsparticles) since this library has no `attract` mouse effect.

**Comment by anthonycmain** [comment]
Thanks really useful
