### ISSUE TITLE
Can't change opacity on image

### ISSUE THREAD

**Issue by ghost** [VincentGarreau/particles.js#493]
Hello, it seems like we can't change the opacity of particle when selecting the image option, could you please add it? Thanks a lot for reading.

**Comment by markwrightdev** [comment]
> Hello, it seems like we can't change the opacity of particle when selecting the image option, could you please add it? Thanks a lot for reading.

#168 was already opened about that, but this project looks abandoned. I’ve migrated to tsparticles few months ago with that feature.
https://github.com/matteobruni/tsparticles

**Comment by ghost** [comment]
Yea I made up my own particle thingy with html and not canvas. Thank u for the help anyway
