### ISSUE TITLE
Can't upload Background Image

### ISSUE THREAD

**Issue by lfernandeslucas** [VincentGarreau/particles.js#56]
Hey!

Everything is working perfectly, and it's a very nice job. Thank you!

But I have an issue, I can't add no bg image... I can change the bg collor, but every image I add, it simply won't load, keeping the bg collor only.

Probably I'm doing something wrong...

Can you guys help me, please?

Thank you again!

**Comment by VincentGarreau** [comment]
Hey @lfernandeslucas,

Thanks! You can't set a background-image (or background-color) into the particles.js configuration. You can set it to a HTML element, the #particles-js div for example: http://codepen.io/anon/pen/EjNpzM

Vincent.
