### ISSUE TITLE
How to destroy a pJS object?

### ISSUE THREAD

**Issue by cnjsstong2** [VincentGarreau/particles.js#63]
In IE, it will continue to call raf even after the DOM destroyed. Is there any way to manually destroy a pJS object?

**Comment by VincentGarreau** [comment]
HI @cnjsstong2,

You can destroy the pJS by this way : window.pJSDom[0].pJS.fn.vendors.destroypJS()
Sorry for my late reply, hope it helps!

**Comment by cnjsstong2** [comment]
@VincentGarreau Thanks!

**Comment by maxfriedmann** [comment]
If you're in a singe page application and might want to start rendering again you have to re-initialize the window.pJSDom array again since .destroypJS removes it completely. 

Safest way for me is : 
```
if (window["pJSDom"] instanceof Array && window["pJSDom"].length > 0) {
    for (let i = 0; i < window["pJSDom"].length; i++)
        window["pJSDom"][i].pJS.fn.vendors.destroypJS();
    window["pJSDom"] = [];
}
```

**Comment by RainierMallol** [comment]
In my case, as I'm only using one particle.js object and I'm sure I'll be using only one, I edited @maxfriedmann code to

```  
window.pJSDom[0].pJS.fn.vendors.destroypJS();
window["pJSDom"] = [];
```

**Comment by naturalethic** [comment]
This needs to be in the README

**Comment by Dok11** [comment]
Seems like `destroypJS() `destroy of all instances from particlesJs. Not only zero element like in your example

**Comment by Moondiidev** [comment]
Wtf is pjsDOM??? there is no mention of it in the readme.md
