### ISSUE TITLE
what is the browser support for this 

### ISSUE THREAD

**Issue by landed1** [VincentGarreau/particles.js#72]
If you can add this to the docs that would be great..I don't see this being canvas but I would like to know how far back this works...

**Comment by VincentGarreau** [comment]
Hi @landed1! I didn't check all the browser versions, but technically all the browsers that support canvas should work: http://caniuse.com/#feat=canvas (doesn't work on IE8)
I'll add it into the README, thanks!

**Comment by landed1** [comment]
Thank you Vincent.
