### ISSUE TITLE
Changing the JSON info

### ISSUE THREAD

**Issue by IngvarOlsen** [VincentGarreau/particles.js#73]
Hey man, really love your work. 
I just have a small problem with updating some of the values in the JSON file.
What I've used so far, is just what you wrote in a closed issue;

pJSDom[0].pJS.particles.number.value = 1000;
pJSDom[0].pJS.particles.move.direction = "bottom";
pJSDom[0].pJS.particles.color.value= "#766637";
pJSDom[0].pJS.fn.particlesRefresh(); 

But there is some value I can't change such as;
particles.move.speed
particles.size.value

And I've written them in the same with as those value changes that actually work, like;
pJSDom[0].pJS.particles.move.speed = 9;
pJSDom[0].pJS.fn.particlesRefresh();

Am I doing something totally wrong here? :s
Also sorry for bothering you.

**Comment by VincentGarreau** [comment]
Hey @IngvarOlsen, thanks :)

To support the retina display some values like "moves.speed" and "size.value" are stored into pJSDom[0].pJS.tmp.obj

If you want to update theses values just update the tmp values, for example:

pJSDom[0].pJS.tmp.obj.move.speed = 9;
pJSDom[0].pJS.tmp.obj.size_value = 10;
pJSDom[0].pJS.fn.particlesRefresh();

Hope it helps!

**Comment by IngvarOlsen** [comment]
Ohh alright, thanks dude!

**Comment by NJseo** [comment]
I still can't get this to work, I want to simulate a mouse down event and nothing seems to be happening. I tried all sorts of combinations. If you could help that would be great.
