### ISSUE TITLE
pJSDom[0].pJS.fn.vendors.start() will increase the move speed

### ISSUE THREAD

**Issue by YanshuoH** [VincentGarreau/particles.js#86]
Hello,

It seems that when I call ``` pJSDom[0].pJS.fn.vendors.start() ```, all particles speed up with a certain ratio.

Normal?

**Comment by VincentGarreau** [comment]
Hi!

Yep, this method doesn't call cancelRequestAnimFrame.

If you want to refresh particles, you can do this: pJS.fn.particlesRefresh();

Details:
```
pJS.fn.particlesRefresh = function(){

    /* init all */
    cancelRequestAnimFrame(pJS.fn.checkAnimFrame);
    cancelRequestAnimFrame(pJS.fn.drawAnimFrame);
    pJS.tmp.source_svg = undefined;
    pJS.tmp.img_obj = undefined;
    pJS.tmp.count_svg = 0;
    pJS.fn.particlesEmpty();
    pJS.fn.canvasClear();

    /* restart */
    pJS.fn.vendors.start();

};
```

**Comment by YanshuoH** [comment]
Hello,

Thank you for your reply!

I was intended to do a pause/resume, but well, a refresh will be fine.
