### ISSUE TITLE
Changing the size and color of each shape

### ISSUE THREAD

**Issue by MHM5000** [VincentGarreau/particles.js#9]
Maybe it could be added?
this is the options that I would provide:
+ increase/decrease (size)
    + active / inactive
    + for each particle differently
    + for all particles the same:
        + increase
        + decrease
        + random (increase || decrease)
    + duration

+ change of color:
    + array of colors
     for example `[#fee, #fcc, #a00, #fee]`
    + the `easeIn` || `easeInOut` option
    + speed

And one more thing, ... automate the `min` version with grunt...

**Comment by VincentGarreau** [comment]
Increase / decrease size + Array of colors added in the 2.0.0 version ;)
https://github.com/VincentGarreau/particles.js/releases/tag/2.0.0

**Comment by akodiaemma** [comment]
dude you are the best. words can not describe. thanks a lot man

**Comment by geekykeshav** [comment]
Can anyone help me ?
I want to set random color in line linked to the particles, but i don't know how to do this.

**Comment by Jamiroquail** [comment]
This is helping me make my beginner portfolio look slick! Thanks a lot.
